// Route66Angular/src/app/input-field/input-field.component.ts
import { Component, Input } from '@angular/core';
import { FieldData } from "../models/field-data";
import { NgStyle } from "@angular/common";

@Component({
  selector: 'app-input-field',
  standalone: true,
  imports: [
    NgStyle
  ],
  templateUrl: './input-field.component.html',
  styleUrl: './input-field.component.css'
})
export class InputFieldComponent {

  @Input({required: true}) fieldData!: FieldData;
}

<input [ngStyle]="{ 'left.ch': fieldData.col, 'width.ch': fieldData.length }"
       [(ngModel)]="fieldData.value"
       (ngModelChange)="valueChanged($event)"
       (focus)="onFocus()"
/>

// route66-react/src/components/InputField/InputField.jsx
import styles from './InputField.module.css';

export default function InputField({fieldData, valueChanged, inputFocused }) {

    const style = {
        left: fieldData.col + 'ch',
        width: fieldData.length + 'ch',
    }

    return (
        <input
            style={style}
            value={fieldData.value}
            onInput={(event) => valueChanged(fieldData.row, fieldData.col, event.target.value)}
            onFocus={(event) => inputFocused(fieldData.row, fieldData.col)}
        />);

}
