// route66-vue/src/components/InputField/InputField.vue
<script lang="ts">
export { default } from './InputField.js'
</script>

<template>
  <input :style="positionStyle"
         :data-testid="testId"
         @input="(event) => $emit('inputChanged', fieldData.row, fieldData.col, event.target.value)"
         @focus="$emit('focusChanged', fieldData.row, fieldData.col)">
</template>

<style scoped>

</style>

// route66-react/src/components/InputField/InputField.jsx
export default function InputField({fieldData, valueChanged, inputFocused }) {

    const style = {
        left: fieldData.col + 'ch',
        width: fieldData.length + 'ch',
    }

    return (
        <input
            style={style}
            value={fieldData.value && fieldData.value.trim().length === 0 ? "" : fieldData.value}
            onInput={(event) => valueChanged(fieldData.row, fieldData.col, event.target.value)}
            onFocus={(event) => inputFocused([fieldData.row, fieldData.col])}
        />);

}
