// Route66Angular/src/app/label-field/label-field.component.ts
import { Component, Input } from '@angular/core';
import { FieldData } from "../models/field-data";
import { NgStyle } from "@angular/common";

@Component({
  selector: 'app-label-field',
  standalone: true,
  imports: [
    NgStyle
  ],
  templateUrl: './label-field.component.html',
  styleUrl: './label-field.component.css'
})
export class LabelFieldComponent {

  @Input({required: true}) fieldData!: FieldData;
}

<span class="field" [ngStyle]="{ 'left.ch': fieldData.col }">{{fieldData.value}}</span>

// route66-react/src/components/LabelField/LabelField.jsx
import styles from './LabelField.module.css';

export default function LabelField({ fieldData }) {

    const style = {
        "left": fieldData.col + 'ch'
    };

    const testId = `${fieldData.row}-${fieldData.col}`

    return (
        <span className={styles.field}
              style={style}
              data-testid={testId}>
            {fieldData.value}
        </span>
    );
}
