// route66-react/src/InputField.jsx
import styles from './css/InputField.module.css';

export default function InputField({fieldData, valueChanged }) {

    const style = {
        left: fieldData.col + 'ch',
        width: fieldData.length + 'ch',
    }

    return (
        <input
            style={style}
            value={fieldData.value}
            onInput={(event) => valueChanged(event.target.value)}
        />);

}

// route66-vue/src/components/InputField/InputField.vue
<script lang="ts">
export { default } from './InputField.js'
</script>

<template>
  <input :style="positionStyle"
         :data-testid="testId"
         @input="(event) => $emit('inputChanged', fieldData.row, fieldData.col, event.target.value)"
         @focus="$emit('focusChanged', fieldData.row, fieldData.col)">
</template>

<style scoped>

</style>
