// route66-react/src/components/Row/Row.jsx
import LabelField from "../LabelField/LabelField";
import styles from './Row.module.css';
import InputField from "../InputField/InputField";


export default function Row({ i, fieldData = [], inputChanged, focusChanged })  {

    const fields = fieldData.map((field, i) => {
        if(field.isProtected) {
            return <LabelField key={`${i}-${field.col}`} fieldData={field}></LabelField>
        } else {
            return <InputField key={`${i}-${field.col}`}
                               fieldData={field}
                               valueChanged={inputChanged}
                               inputFocused={focusChanged}>
                   </InputField>
        }
    })

    return (<div className={styles.row}>{fields}</div>)
}

// route66-vue/src/components/Row/Row.vue
<script lang="js">
  export { default } from './Row.js'
</script>

<template>
  <div class="row">
    <template v-for="field in fieldData" v-bind:key="`${i}-${field.col}`">
      <LabelField v-if="field.isProtected" :fieldData="field"/>
      <InputField v-else
                  :fieldData="field"
                  @inputChanged="(row, col, value) => $emit('inputChanged', row, col, value)"
                  @focusChanged="(row, col) => $emit('focusChanged', row, col)"/>
    </template>
  </div>
</template>

<style scoped>

</style>
