// Route66Angular/src/app/terminal/terminal.component.ts
import { Component } from '@angular/core';
import { Route66Service } from "../services/Route66Service";
import { FieldData } from "../models/field-data";
import { Observer } from "rxjs";

@Component({
  selector: 'app-terminal',
  standalone: true,
  imports: [],
  templateUrl: './terminal.component.html',
  styleUrl: './terminal.component.css'
})
export class TerminalComponent {



  constructor(private route66Service: Route66Service) {}

  ngOnInit(): void {
    this.route66Service.startTerminalPolling({
      next(fieldData : FieldData[][]) {
        console.info(fieldData);
      },
      error(err: any) {
        console.error(err);
      },
      complete() {}
    });
  }
}



<div id="container" class="border-zero" tabindex="0" (keyup.enter)="enter()">
  <div>
    <button class="keypad-button" (click)="reset()">Reset</button>
    <button class="keypad-button" (click)="functionKey(Aid.PA1)">PA1</button>
    <button class="keypad-button" (click)="functionKey(Aid.PA2)">PA2</button>
    <button class="keypad-button" (click)="functionKey(Aid.PA3)">PA3</button>
    <button class="keypad-button" (click)="functionKey(Aid.SYSREQ)">Sys Req</button>
    <button class="keypad-button" (click)="functionKey(Aid.CLEAR)">Clear</button>
  </div>
  <div>
    <button class="keypad-button" (click)="functionKey(Aid.PF1)">PF1</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF2)">PF2</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF3)">PF3</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF4)">PF4</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF5)">PF5</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF6)">PF6</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF7)">PF7</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF8)">PF8</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF9)">PF9</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF10)">PF10</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF11)">PF11</button>
    <button class="keypad-button" (click)="functionKey(Aid.PF12)">PF12</button>
  </div>

  <app-row *ngFor="let data of fieldData; index as i"
           [index]="i"
           [fieldData]="data"
           (focused)="onFocusChanged($event)">
  </app-row>
  <div *ngIf="wait" class="wait"></div>
  <p *ngIf="errorMessage" class="error">{{errorMessage}}</p>
</div>

// route66-vue/src/components/Terminal/Terminal.vue
<script lang="js">
  export { default } from './Terminal.js'
</script>

<template>
  <div id="container" class="border-zero">
    <div>
      <button class="keypad-button">Reset</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PA1)">PA1</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PA2)">PA2</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PA3)">PA3</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.SYSREQ)">Sys Req</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.CLEAR)">Clear</button>
    </div>
    <div>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF1)">PF1</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF2)">PF2</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF3)">PF3</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF4)">PF4</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF5)">PF5</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF6)">PF6</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF7)">PF7</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF8)">PF8</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF9)">PF9</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF10)">PF10</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF11)">PF11</button>
      <button class="keypad-button" @click="functionKey(Constants.AID.PF12)">PF12</button>
    </div>
    <div>
      <Row v-for="(row, i) in rows"
           :key="i"
           :i="i"
           :fieldData="row"
           @inputChanged="inputChanged"
           @focusChanged="focusChanged">
      </Row>
    </div>
    <div v-if="errorMessage" class="error">{{errorMessage}}</div>
  </div>
</template>

<style scoped>

</style>
